---
abstract: 'Provide commonly requested regular expressions'
author:
  - 'Abigail <regexp-common@abigail.be>'
build_requires:
  ExtUtils::MakeMaker: 0
  strict: 0
configure_requires:
  ExtUtils::MakeMaker: 0
  strict: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
keywords:
  - 'regular expression'
  - pattern
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Regexp-Common
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.00473
  strict: 0
  vars: 0
resources:
  repository: git://github.com/Abigail/Regexp--Common.git
version: 2013031301
x_test_requires:
  strict: 0
